import { Recommend } from "./types";

export const initRecommendList: Array<Recommend> = [
  {
    id: 0,
    userName: "테오",
    favorite: 200,
    share: 60,
    nodes: [{}],
    description: {},
    develop: 0, 
  },
  {
    id: 1,
    userName: "설아아빠",
    favorite: 130,
    share: 45,
    nodes: [{}],
    description: {},
    develop: 1, 
  },
  {
    id: 2,
    userName: "알모",
    favorite: 120,
    share: 77,
    nodes: [{}],
    description: {},
    develop: 0, 
  },
  {
    id: 3,
    userName: "단테",
    favorite: 160,
    share: 58,
    nodes: [{}],
    description: {},
    develop: 1, 
  },
  {
    id: 4,
    userName: "홀리몰리",
    favorite: 160,
    share: 58,
    nodes: [{}],
    description: {},
    develop: 2, 
  },
  {
    id: 5,
    userName: "이엘로",
    favorite: 178,
    share: 25,
    nodes: [{}],
    description: {},
    develop: 1, 
  },
  {
    id: 6,
    userName: "데비니",
    favorite: 124,
    share: 29,
    nodes: [{}],
    description: {},
    develop: 2, 
  },
]
